### ISSUE TITLE
GitHub Actions not running devs

### ISSUE THREAD

**Issue by fgrunewald** [marrink-lab/vermouth-martinize#387]
@pckroon I think that also here in martinize2 github actions is not installing the dev packages but rather running on the latest python version. If you could quickly check then I'll raise an issue.

**Comment by pckroon** [comment]
```
Run actions/setup-python@v2
  with:
    python-version: 3.7-dev
    token: ***
  env:
    VERMOUTH_TEST_DSSP: mkdssp
    SKIP_GENERATE_AUTHORS: 1
    SKIP_WRITE_GIT_CHANGELOG: 1
Successfully setup CPython (3.9.6)
```
Indeed. non-dev (e.g. python-3.7) does work as intended though.
